#!/bin/bash

(
	head -n5 page.html | tr -d '\n	';
	echo -n "<script type=\"module\">";
	jspacker -i "/$(grep "<script" page.html | sed -e 's/.*src="\([^"]*\)".*/\1/')" -n | terser -m  --module --compress pure_getters,passes=3 --ecma 6 | tr -d '\n';
	echo -n "</script>";
	tail -n5 page.html | tr -d '\n	';
) > "index.html";
